[File]
RunDir = "/hdd/SBC-Queens-SiPMs-Runs"
# Number of waveforms to take and save to file when in run mode
RunWaveforms = 200000
# Number of waveforms to take and save to file when in breakdown voltage mode
GainWaveforms = 20000

[Teensy]
Port = "/dev/ttyACM0"

# RTD sampling period in ms
RTDSamplingPeriod = 1000

RTDNames = ["SiPM (1)", "SiPM (2)", "Water Block"]

PIDEnable = false
PeltierTempSetpoint = -20

PeltierTKp = -500
PeltierTTi = 1000000.0
PeltierTTd = 0.0

[CAEN]
# DT5730B, DT5740D or V1740D
Model = "V1740D"
Port = 23473
# USB if using a direct USB connection
# A4818 for the USB 3.0 to CONET adapter
ConnectionType = "A4818"
# if applicable
VMEAddress = 0x0
# 0 = not allowed
RecordLength = 100
MaxEventsPerRead = 500
PostBufferPorcentage = 90
OverlappingRejection = false
TRGINasGate = false
# 0 = disabled, 1 = ACQ only, 2 = ext mode only, 3 = both
ExternalTrigger = 3
SoftwareTrigger = 3
# 0 = rising edge, 1 = falling edge
Polarity = 1
# 0 = NIM, 1 = TTL
IOLevel = 0

# Individual Channel settings
# The number after group represents
# the # of the group (or channel)
[CAEN.group0]
Enabled = true
# Trigger Enable Mask
# TrgMask = 7
TrgMask = 0b11111111
# Acquisition Enable Mask
AcqMask = 0b11111111
# Group offset
Offset = 0x8000
# Individual corrections to offset
Corrections = [5, 0, 6, 0, 0, 0, 0, 0]

Range = 0
Threshold = 0x0800

[CAEN.group1]
Enabled = true
# Trigger Enable Mask
# TrgMask = 7
TrgMask = 0b11111111
# Acquisition Enable Mask
AcqMask = 0b11111111
# Group offset
Offset = 0x8000
# Individual corrections to offset
Corrections = [5, 0, 6, 0, 0, 0, 0, 0]

Range = 0
Threshold = 0x0800

[Other]
[Other.SiPMVoltageSystem]
Port = "/dev/ttyUSB0"
InitVoltage = 52.0

[Other.PFEIFFERSingleGauge]
Port = "COM7"
Enabled = false
# 0 = 100ms, 1 = 1s, 2 = 1min
Rate = 1
