[File]
RunDir = "C:\\Users\\SBC\\Documents\\SIPM-Testing-Software"
RunName = "RUNS"

[Teensy]
Port = "COM4"

PIDRelay = false
GeneralRelay = false

PID1Enable = false
PID1TempSetpoint = -18
PID1CurrentSetpoint = 5
PID1TKp = -3e3
PID1TTi = 50e3
PID1TTd = 0
PID1AKp = 200
PID1ATi = 100
PID1ATd = 0

PID2Enable = false
PID2TempSetpoint = 0
PID2CurrentSetpoint = 3
PID2TKp = -2000
PID2TTi = 100
PID2TTd = 0
PID2AKp = 200
PID2ATi = 100
PID2ATd = 0

[CAEN]
# DT5730B or DT5740D
Model = "DT5740D"
Port = 0
# 0 = not allowed
RecordLength = 180
MaxEventsPerRead = 500
PostBufferPorcentage = 50
OverlappingRejection = false
TRGINasGate = false
# 0 = disabled, 1 = ACQ only, 2 = ext mode only, 3 = both
ExternalTrigger = 1
SoftwareTrigger = 1
# 0 = rising edge, 1 = falling edge
Polarity = 1
# 0 = NIM, 1 = TTL
IOLevel = 0

# Individual Channel settings
# The number after group represents
# the # of the group (or channel)
[CAEN.group0]
Enabled = 1
# Trigger Enable Mask
TrgMask = 7
# Acquisition Enable Mask
AcqMask = 7
# Group offset
Offset = 0x8000
# Individual corrections to offset
Corrections = [5, 0, 6, 0, 0, 0, 0, 0]

Range = 0
Threshold = 2103

# [CAEN.group1]
# Enabled = 0
# Offset = 0x8000
# Corrections = [0, 0, 0, 0, 0, 0, 0, 0]
# Range = 1
# Threshold = 2075
