[File]
RunDir = "../RUNS"
RunName = "Testing"

[Teensy]
Port = "COM4"

PIDRelay = false
GeneralRelay = false

PID1Enable = false
PID1TempSetpoint = -18
PID1CurrentSetpoint = 5
PID1TKp = -3e3
PID1TTi = 50e3
PID1TTd = 0
PID1AKp = 200
PID1ATi = 100
PID1ATd = 0

PID2Enable = false
PID2TempSetpoint = 0
PID2CurrentSetpoint = 3
PID2TKp = -2000
PID2TTi = 100
PID2TTd = 0
PID2AKp = 200
PID2ATi = 100
PID2ATd = 0

[CAEN]
# DT5730B or DT5740
Model = "DT5730B"
# 0 = not allowed
OverlappingRejection = 0
MaxEventsPerRead = 512
Channel = 0
Offset = 0x8000
RecordLength = 180
# 0 = rising edge, 1 = falling edge
Polarity = 1
Range = 1
PostBufferPorcentage = 50
Threshold = 7500