[File]
RunDir = "./RUNS"
RunName = "COLD_TEST_01"

[Teensy]
Port = "COM5"

# If true, the Teensy is in RTD only mode.
# cannot be changed during GUI
RTDMode = true
# RTD sampling period in ms
RTDSamplingPeriod = 1000
# If bit n is set, it enabled the RTD at position (i, k)
# where i is the board and k is the RTD
# Depends on how many boards and RTDs are in each board.
RTDMask = 0xFFFF
#RTDNames = ["SiPM1", "Block", "SiPM2", "Whatever"]

PIDEnable = false
PeltierTempSetpoint = -30

PeltierTKp = -100
PeltierTTi = 1e6
PeltierTTd = 0

[CAEN]
# DT5730B or DT5740D
Model = "DT5730B"
Port = 1
# 0 = not allowed
RecordLength = 500
MaxEventsPerRead = 500
PostBufferPorcentage = 50
OverlappingRejection = false
TRGINasGate = false
# 0 = disabled, 1 = ACQ only, 2 = ext mode only, 3 = both
ExternalTrigger = 0
SoftwareTrigger = 1
# 0 = rising edge, 1 = falling edge
Polarity = 1
# 0 = NIM, 1 = TTL
IOLevel = 0

# Individual Channel settings
# The number after group represents
# the # of the group (or channel)
[CAEN.group0]
Enabled = 1
# Trigger Enable Mask
TrgMask = 7
# Acquisition Enable Mask
AcqMask = 7
# Group offset
Offset = 0x8000
# Individual corrections to offset
Corrections = [5, 0, 6, 0, 0, 0, 0, 0]

Range = 1
Threshold = 8000

# [CAEN.group1]
# Enabled = 0
# Offset = 0x8000
# Corrections = [0, 0, 0, 0, 0, 0, 0, 0]
# Range = 1
# Threshold = 2075

[Other]
[Other.PFEIFFERSingleGauge]
Port = "COM3"
Enabled = true
# 0 = 100ms, 1 = 1s, 2 = 1min
Rate = 1